version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/cybervision
hooks:
  BeforeInstall:
    - location: scripts/before_install.sh
  AfterInstall:
    - location: scripts/restart_server.sh
      timeout: 300
      runas: ubuntu
